name: Auto review course name 

on: 
  pull_request:
    branches: [ main ]

  workflow_dispatch: 
jobs: 
  auto-review: 
    runs-on: ubuntu-latest 
    env:
      PR_NUMBER: ${{github.event.number}}

    steps: 
      - name: Checkout playbooks
        uses: actions/checkout@v2 
        with: 
          repository: devonfw-tutorials/tutorials 
          path: playbooks 

      - id: changed-files
        uses: jitterbit/get-changed-files@v1

      - name: Check name 
        id: check-name
        run: |
          cd playbooks
          playbook-list=() 
          for dir in */; do playbook-list+=("${dir}"); done

          eq_name_message=""
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            file = "$(echo $changed_file | cut -d/ -f1)"
            if [[ $file =~ *"pathway.json"]]; then
              course_name= ${file%"-pathway.json"}
              if[["${playbook-list[@]} =~ " ${course_name} "]]; then
              eq_name_message+="\n" + ${course_name} + " exist already. \n"
              fi
            fi
          done

          echo "::set-output name=eq_name_message::$eq_name_message"

      - name: Request changes 
        if:  ${{ steps.check-name.outputs.eq_name_message != '' }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: REQUEST_CHANGES
          body: ${{ steps.get_message.outputs.message}} + " You just tried to name a course after a playbook.\n Please change the course name. \n"