name: Auto review course name 

on: 
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs: 
  auto-review: 
    runs-on: ubunto-latest 
    steps: 
      - name: Checkout playbooks
        uses: actions/checkout@v2 
        with: 
          repository: devonfw-tutorials/tutorials 
          path: playbooks 
      - id: changedfiles
        uses: jitterbit/get-changed-files@v1
      - name: Check name 
        id: check-name
        run: |
          playbooks =()
          cd playbooks
          for dir in */; do
            playbooks += ($dir)
          
          eq_name_message = ""
          for changed_file in ${{ steps.changedfiles.output.all}}; do
            file = "$(echo $changed_file | cut -d / -f 1)"
            if [[ $file == *"pathway.json"]]; then
              course_name = ${file%"-pathway.json"}
              if[["${playbooks[@]} =~ " ${course_name}"]]; then
              eq_name += "\n" + ${course_name} + " exist already. \n"
              fi
            fi
          done

          echo "::set-output name=eq_name_message::$eq_name_message"

      - name: Request changes 
        if:  ${{ steps.get_message.outputs.eq_name_message != '' }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: REQUEST_CHANGES
          body: ${{ steps.get_message.outputs.message + " You just tried to name a course after a playbook.\n Please change the course name. \n"}}