name: Auto review course name 

on: 
  pull_request:
    branches: [ main ]

  workflow_dispatch: 
jobs: 
  auto-review: 
    runs-on: ubuntu-latest 
    env:
      PR_NUMBER: ${{github.event.number}}

    steps: 
      - name: Checkout playbooks
        uses: actions/checkout@v2 
        with: 
          repository: devonfw-tutorials/tutorials 
          path: playbooks 

      - id: changedfiles
        uses: jitterbit/get-changed-files@v1

      - name: Check name 
        id: check-name
        run: |
          cd playbooks
          playbook_list=()
          for dir in */; do 
            playbook_list+=("${dir::-1}"); 
          done
            echo ${playbook_list[@]}
          for changed_file in ${{ steps.changedfiles.outputs.all }}; do
            echo changed_file
          done

      - name: Request changes 
        if:  ${{ steps.check-name.outputs.eq_name_message != '' }}
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: REQUEST_CHANGES
          body: ${{ steps.get_message.outputs.message}} + " You just tried to name a course after a playbook.\n Please change the course name. \n"